### ISSUE TITLE
Survivor perk "Fixated" (aka Self-Aware) showing up as other perks

### ISSUE THREAD

**Issue by BritoSupreme** [KiKoS0/dbd-tooltips#339]
The perk Fixated was showing up as Distortion and then later as Counterforce after refreshing during Otzdarva's stream. Surge is also showing up as Play With Your Food. Possibly all Stranger Things related perks are broken.

**Comment by KiKoS0** [comment]
Unfortunately that's the main drawback of using image recognition on compressed Twitch streams: The accuracy loss when the bitrate drops which leads to misidentifying perks, especially ones with little detail to begin with.
