### ISSUE TITLE
Add new locale

### ISSUE THREAD

**Issue by PrincipleZ** [KiKoS0/dbd-tooltips#60]
Hi, I want to contribute new locales but it seems that the locale files are hosted on the CDN. How can I contribute to it? Thanks

**Comment by KiKoS0** [comment]
Hey I have private scripts that run for each supported locale, I'll need to make that repository public and you can contribute to it if you wish. I can let you know once it's ready.

**Comment by KiKoS0** [comment]
@PrincipleZ Took a while but I finally found time to make it public,

https://github.com/KiKoS0/dbd-tooltips-tooling/tree/master/dbd_tooling/fetch/locales
